### ISSUE TITLE
style.md typo?

### ISSUE THREAD

**Issue by chuntaro** [LispLang/lisplang.github.io#36]
I think defconstant is better than defparameter.
~~~lisp
(defconstant +golden-ratio+ 1.6180339)

(defconstant +allowed-operators+ '(+ - * / expt))
~~~

**Comment by PuercoPop** [comment]
@chuntaro reloading a file with `(defconstant +allowed-operators+ '(+ - * / expt))` is going to run into problems (signals `defconstant-uneql` in SBCL f/e). defparameter is fine, plus the point of that section is to show how variables should be named not if one shoul use `defvar`/`defparameter`/`defconstant`/`alexandria:define-constant`

**Comment by chuntaro** [comment]
I see. It was very well understood.
Thank you for easy-to-understand explanation.
