### ISSUE TITLE
Open source success stories ?

### ISSUE THREAD

**Issue by vindarel** [LispLang/lisplang.github.io#42]
Hi,
I can see impressive CL software on the success stories page, but no open source ones. Do you have some to share, at least here ? Even simple websites with a CL base ?

Thanks

I only came across [Turtl](https://github.com/turtl).

(and keep up your impressive work)

**Comment by eudoxia0** [comment]
There are some open source success stories: pgloader and Maxima. I tried to focus on large-scale, commercially successful projects, however, since that's most relevant to the prospective Lisp user.
