### ISSUE TITLE
HTTPS: invalid certificate

### ISSUE THREAD

**Issue by phoe** [LispLang/lisplang.github.io#58]
![screenshot from 2018-10-03 16-00-42](https://user-images.githubusercontent.com/15045546/46415429-9312cb80-c725-11e8-9b30-454c1194223a.png)

**Comment by eudoxia0** [comment]
Yes, GitHub doesn't serve pages over SSL. I think it's solveable, suggestions welcome.

**Comment by PuercoPop** [comment]
It does serve pages over SSL for custom domains now! https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by eudoxia0** [comment]
Interesting, it says I can't enable it because it's misconfigured, I'll look into this after I leave work.

**Comment by eudoxia0** [comment]
Alright, the certificate is being issued or something and it should take 24 hours. Thanks guys!

**Comment by eudoxia0** [comment]
![2018-10-04-194931_1920x1080_scrot](https://user-images.githubusercontent.com/1612511/46507428-cf6e2680-c80e-11e8-9855-45a505d3aee9.png)
