### ISSUE TITLE
The list of recommend libraries is lagging behind

### ISSUE THREAD

**Issue by vindarel** [LispLang/lisplang.github.io#69]
Hi Fernando,

The list is lagging behind: https://lisp-lang.org/wiki/article/recommended-libraries

- Integral is deprecated and replaced by Mito
- your Crane ORM looks unmaintained so does it belong here
- there are more Python bridges than burggled-batteries
- GUI mentions XUL bindings, doesn't mention Qtools, Ltk or IUP
- there are great new libs for concurrent/async programming (cl-gserver…)
- etc

The awesome-cl list is more comprehensive (could be a cons) and has more helping eyes and hands.

What do you want to do about this?

Best

**Comment by eudoxia0** [comment]
Thanks for pointing this out. It makes more sense to link to `awesome-cl`.
