### ISSUE TITLE
Old reference suggested for Windows users getting started

### ISSUE THREAD

**Issue by Jach** [LispLang/lisplang.github.io#74]
https://lisp-lang.org/learn/getting-started/ correctly mentions Portacle as the fastest solution to getting started. The link needs to be updated to https://portacle.github.io/ but I'd still agree with that phrasing.

Under the Windows section, though, I think Portacle should be mentioned once again as the suggested environment. LispStick hasn't had a release since 2013. I'd be in favor of removing the reference to LispStick entirely, but leaving it to honor the contribution is fine so long as its age is appropriately tagged. (The Portacle link should also mention the last release, TBH, which was 2020.)

Additionally https://lispcookbook.github.io/cl-cookbook/editor-support.html could be linked for alternative editors, especially since I would expect many Windows users would prefer to use VS Code. (A very recent [experience report](https://blog.djhaskin.com/blog/experience-report-using-vs-code-alive-to-write-common-lisp/) shows it's quite usable.) The getting started page just sort of assumes the user will be using emacs, and for the linux and OS X crowd even assumes they have it installed already.

I'm happy to freshen up the page and submit a pull request myself, just curious if there are any thoughts about it, or even whether the current page is seen as fine.

**Comment by eudoxia0** [comment]
Addressed here:

- https://github.com/LispLang/lisplang.github.io/commit/0431962beed33c2c6b42ea1d0d67c6ea1f344ce5
- https://github.com/LispLang/lisplang.github.io/commit/d4caca95a19a771b3b6a18148a90e1a17a77a406

**Comment by Jach** [comment]
Awesome, thank you!
